### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by umairali** [davibennun/laravel-push-notification#43]
I am trying to install with Laravel 5 but i am facing installation error

**Comment by ClaudioMeinberg** [comment]
The solution for your issue seems to be here... https://github.com/davibennun/laravel-push-notification/issues/34 

Laravel 5 version is now available at laravel5 branch, you can require it on composer:
"davibennun/laravel-push-notification": "dev-laravel5"
The way you use this package is the same, the only thing changed was the config file location, once you published it using php artisan vendor:publish the config file goes to app/config/push-notification.php

**Comment by kuez** [comment]
+ 1
